# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo Build First Job!

    - job: SecondJob
      steps:
      - bash: echo Build Second Job!

  - stage: devDeploy
    dependsOn: Build
    jobs:
    - job: devDeployJob
      steps:
      - bash: echo devDeployJob!

  - stage: OnDeploy
    dependsOn: Build
    jobs:
    - job: OnDeployJob
      steps:
      - bash: echo onDeployJob!

  - stage: ProdDeploy
    dependsOn:
    - devDeploy
    - OnDeploy
    jobs:
    - job: ProdDeployJob
      steps:
      - bash: echo ProdDeployJob!
